version: '3.3'
services:
  nginx:
    container_name: nginx
    build: ./entrypoint
    ports:
      - 80:80
    restart: always

  melanoma_executor:
    container_name: melanoma_executor
    build: ./melanoma_executor
    command: gunicorn --bind 0.0.0.0:5001 app:app
    volumes:
      - ./melanoma_executor/:/usr/src/app/
    ports:
      - 5001:5001
    restart: always

  plot_executor:
    container_name: plot_executor
    build: ./plot_executor
    command: gunicorn --bind 0.0.0.0:5002 app:app
    volumes:
      - ./plot_executor/:/usr/src/app/
    ports:
      - 5002:5002
    restart: always