version: '3.3'
services:
  nginx:
    container_name: nginx
    build: ./entrypoint
    ports:
      - 80:80
    restart: always

  model_executor:
    container_name: model_executor
    build: ./model_executor
    command: gunicorn --bind 0.0.0.0:5001 app:app
    volumes:
      - ./model_executor/:/usr/src/app/
    ports:
      - 5001:5001
    restart: always

  plots_executor:
    container_name: plots_executor
    build: ./plots_executor
    command: gunicorn --bind 0.0.0.0:5002 app:app
    volumes:
      - ./plots_executor/:/usr/src/app/
    ports:
      - 5002:5002
    restart: always